// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mmcc.CrashAlert.Database;

#nullable disable

namespace Mmcc.CrashAlert.Migrations
{
    [DbContext(typeof(CrashAlertContext))]
    [Migration("20211219224725_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Mmcc.CrashAlert.Database.ProcessedCrashLog", b =>
                {
                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeProcessed")
                        .HasColumnType("TEXT");

                    b.HasKey("FilePath");

                    b.ToTable("ProcessedCrashLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
